### ISSUE TITLE
Build fails on go1.11

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-engine#100]
**Description**

Building `balena` on ArchLinux, which ships go 1.11 now by default, results in `relocation target runtime.support_avx not defined` and `relocation target runtime.support_avx2 not defined` errors from go crypto.

**Steps to reproduce the issue:**

1. On ArchLInux (or any other system) install go 1.11
2. build balena according to to instructions

**Describe the results you received:**

```
...
---> Making bundle: binary-balena (in bundles/binary-balena)
Building: bundles/binary-balena/balena-v17.12.0-9-gebfc24009
# github.com/docker/docker/cmd/balena
github.com/docker/docker/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/docker/docker/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined
```

**Describe the results you expected:**

Balena building correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
$ go version  
go version go1.11 linux/amd64
```

**Version info**

Building `v17.12.0-9-gebfc24009`, that is the current tip of the `17.12-resin` branch.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

ArchLinux up to date version, building this package https://aur.archlinux.org/packages/balena/

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_i1wb)

**Comment by alexgg** [comment]
Balena Engine is now building on Go 1.16
