### ISSUE TITLE
Error running image: exec: "docker-proxy": executable file not found in $PATH

### ISSUE THREAD

**Issue by nagarashish** [balena-os/balena-engine#107]
I am getting error Error running image: exec: "docker-proxy": executable file not found in $PATH when trying to start the container.  

I don't have docker installed. 

balena version output:
------------------------
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.9
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   c6df57f-unsupported
 Built:        Fri Oct 13 09:31:13 2017
 OS/Arch:      linux/arm
 Experimental: false

I get warning when balenad start:
WARN[0003] failed to retrieve balena-init version: exec: "balena-init": executable file not found in $PATH

What is the proper way to start balenad so it uses balena-proxy instead of docker-proxy?

**Comment by robertgzr** [comment]
Did you try with the latest release :https://github.com/balena-os/balena-engine/releases/tag/v17.12.0

A lot of components of balenaEngine were renamed and we haven't seen that issue yet. Keep in mind that we have seen issues related to manual installation. See #129 for what to look out for...
