### ISSUE TITLE
Dynamically linked binaries

### ISSUE THREAD

**Issue by ntrrg** [balena-os/balena-engine#111]
![image](https://user-images.githubusercontent.com/6060009/46900950-a8e86500-ce78-11e8-9f74-23090ca48b60.png)

Hi, I don't know if this is the desired output, sorry if I am filing this issue unnecessarily.

**Comment by robertgzr** [comment]
Binaries are statically linked since https://github.com/balena-os/balena-engine/releases/tag/v17.12.0

**Comment by ntrrg** [comment]
Great, thanks

**Comment by olljanat** [comment]
As far I see v20.10.20 was still with statically linked binaries but v20.10.26 is no anymore. Change done in purpose or mistake somewhere?

**Comment by lmbarros** [comment]
@olljanat , we reverted back to cgo and dynamic linking in our official builds due to mDNS limitations of the standard pure Go implementation.
