### ISSUE TITLE
Exposing /dev properly to the container by the Engine

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-engine#125]
**Description**

Udev in containers is major pain. Should have a balenaEngine feature, that exposes the devices dynamically in a container, with just udev running in the host.
The discussion went something like:

When a container is privileged, expose a copy of `/dev` to the container in a way that they get dynamic devices (and device names), and exposes it to the container in a way that new devices will show up, but the containers cannot create/destroy nodes (just read/write/open the nodes). This would remove most of the needs of users running udev inside the container.

[From 2018/12/18 architecture call](https://app.frontapp.com/open/cnv_15lkeeb)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_htnf)

**Comment by robertgzr** [comment]
Something that might be worth looking into for ways to support this natively:

http://marc.merlins.org/perso/linux/post_2018-12-20_Accessing-USB-Devices-In-Docker-_ttyUSB0_-dev-bus-usb-_-for-fastboot_-adb_-without-using-privileged.html

**Comment by srlowe** [comment]
This popped up again in a support thread: https://jel.ly.fish/d5b1d2f5-e166-4023-9378-94d718e5d524

**Comment by 20k-ultra** [comment]
We are going to implement this in the Supervisor. See https://github.com/balena-io/balena-supervisor/issues/1532
