### ISSUE TITLE
Add support for build secrets by catching up with the 18.09 Docker CE release

### ISSUE THREAD

**Issue by pdcastro** [balena-os/balena-engine#128]
Catch up with the [18.09 Docker CE release](https://github.com/docker/docker-ce/releases) to provide its [build secrets feature](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information):
> _The new --secret flag for docker build allows the user to pass secret information to be used in the Dockerfile for building docker images in a safe way that will not end up stored in the final image. [...] For example:_
```
# syntax = docker/dockerfile:1.0-experimental
FROM alpine
RUN --mount=type=secret,id=mysecret cat /run/secrets/mysecret # shows secret from default secret location
RUN --mount=type=secret,id=mysecret,dst=/foobar cat /foobar # shows secret from custom secret location
```

Note for anyone browsing and finding this ticket: balena has also an alternative (beta) secrets implementation. It's not currently compatible with the Docker CE feature, but compatibility work is planned. See also issue: https://github.com/balena-io/balena-cli/issues/1063

**Comment by robertgzr** [comment]
Closing as we are based on docker 18.09 with #151 being merged
