### ISSUE TITLE
[Feature] Add a flag to allow fast pulls without the sync guarentees

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-engine#133]
In development mode (localMode) it would be beneficial to have faster image pulls and worry less about layer integrity. It would be good to add a flag to allow the client to request the engine pulls the image without syncing every layer to disc.

**Comment by robertgzr** [comment]
Not an exact solution as it will require an engine restart but we are looking at introducing a daemon flag to disable the additional syncs introduced with https://github.com/balena-os/balena-engine/commit/684d8ba6109c853b355bf11ca3733c4099f14b92

Something like:
```
--disable-durable-pulls			Fallback to default upstream behaviour. Exchanges power-fail safety for pull speed
```

**Comment by robertgzr** [comment]
https://github.com/balena-os/balena-engine/commit/f55774236005a29859948d1e4fc9af58eeb562bf introduces a graphdriver option for `aufs` and `overlay2`. To speed up pulls the daemon can be started with `--storage-opt=overlay2.sync_diffs=false`
