### ISSUE TITLE
Question: ARMv5 builds soft or hard floating point support

### ISSUE THREAD

**Issue by dcflachs** [balena-os/balena-engine#135]
Forgive me if this is something obvious that I have missed but is the ARMv5 release built with soft floating point support or hard floating point support?

**Comment by robertgzr** [comment]
They are compiled with hard floating point support.

You can check that out yourself for any binaries or libraries using [readelf](https://linux.die.net/man/1/readelf). 
Most useful in this case would be the to look at the output of `readelf -A balena-engine`, if it prints something like `ABI_VFP_args: VFP registers` it has support for hardfp.
