### ISSUE TITLE
balena-engine client hangs on first try if the balena-engine daemon is socket activated

### ISSUE THREAD

**Issue by ZubairLK** [balena-os/balena-engine#148]
**Description**

**Steps to reproduce the issue:**
1. Make the balena engine daemon socket activated. e.g. https://github.com/balena-os/meta-balena/pull/1408
2. Try to run a command e.g. `DOCKER_HOST="unix:///var/run/balena-host.sock" balena-engine ps`
3. 

**Describe the results you received:**
The first time `balena-engine ps` command won't run. 

Press ctrl-c, run `DOCKER_HOST="unix:///var/run/balena-host.sock" balena-engine ps` again and it'll work. The balena-engine service has started. But the first command doesn't seem to respond

**Describe the results you expected:**
`DOCKER_HOST="unix:///var/run/balena-host.sock" balena-engine ps` to just work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `balena-engine version`:**

```
root@balena:~# balena-engine version
Client:
 Version:       17.12.0-dev
 API version:   1.35
 Go version:    go1.9.7
 Git commit:    a010e2e2bcd935046d6bcf20aa69e1c93de1c8fc
 Built: Mon Feb 25 12:54:08 2019
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      17.12.0-dev
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.7
  Git commit:   a010e2e2bcd935046d6bcf20aa69e1c93de1c8fc
  Built:        Mon Feb 25 12:54:08 2019
  OS/Arch:      linux/amd64
  Experimental: true
root@balena:~# 

```

**Output of `balena-engine info`:**

```
root@balena:~# balena-engine info   
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 17.12.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 12
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan null
 Log: journald json-file
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-engine-init
containerd version: 
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: 949e6fa-dirty (expected: 949e6facb7738)
Kernel Version: 4.18.14-yocto-standard
Operating System: balenaOS 2.29.2+rev5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 989.2MiB
Name: balena
ID: L5O3:74C2:JDAB:EKFU:HUIQ:325T:QBNZ:B4YQ:XTAZ:XXOM:6UQQ:HKRG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 52
 System Time: 2019-02-25T13:28:56.373033894Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 192.168.1.167:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

balena-engine running inside balenaOS v2.29.2 on an Intel NUC in a VM https://github.com/balena-os/meta-balena/pull/1408

**Comment by robertgzr** [comment]
@ZubairLK 

Looks like you're setting the API host to `-H unix:///var/run/balena-host.sock` on the socket activated balena-host.service

It works as expected for me after replacing it with `-H fd://`

**Comment by ZubairLK** [comment]
Thanks
user-error..
