### ISSUE TITLE
Release files for arm are no longer generated

### ISSUE THREAD

**Issue by i5o** [balena-os/balena-engine#156]
On version `v17.13.0` (latest) there are no tar files for releases. One thing I noticed is that the tags are now being created by resin-ci

this is what I mean:
![image](https://user-images.githubusercontent.com/2650479/55519033-a3602080-564c-11e9-8451-6994aeb0d2e3.png)

prev:
![image](https://user-images.githubusercontent.com/2650479/55519050-aeb34c00-564c-11e9-846b-d2127ccce8d8.png)

**Comment by robertgzr** [comment]
@i5o, we will have a new release with binaries once #151 is merged/tested
