### ISSUE TITLE
Delta creation makes image with "t:latest" tag if no tag is provided

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-engine#178]
**Description**

When running `balena-engine image delta ...`, it will create a delta with `t:latest` tag if no `--tag` is supplied. 

**Steps to reproduce the issue:**
1. have two images
2. calculate delta between them with `balena-engine image delta <image1> <image2>`
3. See how `Successfully tagged t:latest`

**Describe the results you received:**

When running `balena-engine image delta ...`, it will create a delta with `t:latest` tag if no `--tag` is supplied. 

**Describe the results you expected:**

Feels like no tag should be applied to the image unless `--tag` is set explicitly.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `balena-engine version`:**

```
Client:
 Version:           v18.9.7
 API version:       1.39
 Go version:        go1.12.7
 Git commit:        87ef8e0dc-unsupported
 Built:             Mon Jul 22 16:28:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          v18.9.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.7
  Git commit:       87ef8e0dc-unsupported
  Built:            Mon Jul 22 16:28:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `balena-engine info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: v18.9.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null
 Log: journald json-file local
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: runc bare
Default Runtime: runc
Init Binary: balena-engine-init
containerd version: 
runc version: b3d5036b6520060db00c81352d533a5dd919aaaf
init version: N/A (expected: )
Kernel Version: 5.2.5-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 19.34GiB
Name: hydra
ID: X4SL:4L5J:4NH5:QDK5:CRWI:DJEI:BXDV:WD5P:A423:Y6WC:ET7U:FFKA
Docker Root Dir: /var/lib/balena-engine
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* physical, ArchLinux

**Comment by robertgzr** [comment]
Haha when implementing the delta feature I made a mistake when adding the flag to the cli codebase that made `"t"` the default value for `--tag`, when I intended to make `-t` an alias of `--tag`
