### ISSUE TITLE
Silent [xyz blob data] log messages

### ISSUE THREAD

**Issue by zrzka** [balena-os/balena-engine#179]
Not sure how useful those messages are ...

```
Aug 07 18:29:59 5347364 balenad[2110]: [71B blob data]
```

... but sometimes there's a lot of them and it's causing log rotation, etc. Can we filter / disable them?

**Comment by shaunmulligan** [comment]
@zrzka these are actually the logs from the users containers. You can have journalctl expand them if you do `journalctl -u balena -a`

**Comment by robertgzr** [comment]
@shaunmulligan @zrzka I was just going to comment the same...

I do agree that I sometimes like to see what balena-engine is doing without user app logs in between, https://github.com/systemd/systemd/issues/2720 would be really useful for that. But until then `journalctl -u balena -t balenad` works (it won't show logs from containerd though)

**Comment by shaunmulligan** [comment]
@robertgzr have we discussed not logging user app logs to journal? I know we did it on purpose but it doesn't feel that useful for us these days and probably would give us better use of persistent logging (since the 8mb limit often gets over run with user logs). Ill raise it for an arch call.

**Comment by zrzka** [comment]
Ah, didn't know this. Thanks! Learned something new.
