### ISSUE TITLE
The engine fails to clean up unused overlays

### ISSUE THREAD

**Issue by roman-mazur** [balena-os/balena-engine#193]
We have seen a case when device data partition was filled up with overlay folders used by a big user image that was re-downloaded multiple times. Those overlays were kept after deleting running containers and all user images registered in the engine.

**Comment by roman-mazur** [comment]
We also need a tool that can detect unused overlays and delete them to fix affected devices.

**Comment by roman-mazur** [comment]
Today we faced a similar case with the engine running on RPi with aufs.
The mitigation is to collect used aufs IDs (using `cache-id` file of each image layer) and detect unused directories, then deleting them.

**Comment by robertgzr** [comment]
It looks like what we are hitting here is a manifestation of https://github.com/moby/moby/issues/6354 or something very similar.

Basically the way docker handles it's internal representation of which layers it has and the on-disk layer itself is non-atomic, which means events such as power cuts or watchdog related restarts can lead to an incomplete transaction.

**Comment by robertgzr** [comment]
I would like to collect a range of affected versions to see if anything has lead to the increase in reports of this.

When attaching support threads here, please comment with the affected OS version and if delta pulls are used on the device.

**Comment by roman-mazur** [comment]
Waiting for the OS release before we close this.

**Comment by robertgzr** [comment]
released as part of v2.49.0 https://github.com/balena-os/meta-balena/tree/v2.49.0

**Comment by pipex** [comment]
Sorry, I linked the issue on JF and it got reopened. The user was indeed using 2.48.x so it doesn't warrant reopening the ticket
