### ISSUE TITLE
wish: include the local log-driver

### ISSUE THREAD

**Issue by nahuel** [balena-os/balena-engine#194]
Currently balena-engine includes the `json-file` log driver but not the `local` one. The `local` driver uses less disk space so is better for embedded systems (e.g., when using balena-engine without balena supervisor). Will be nice to include it in the standard distribution.

**Comment by robertgzr** [comment]
This sounds reasonable. I will see that we enable it with 19.03. (see #188 for progress on that)

**Comment by robertgzr** [comment]
support for the local logdriver is back with 19.03.11 https://github.com/balena-os/balena-engine/blob/1fe708d1b4e01e0ecd567b85eb6c81593c8a8bb5/daemon/logdrivers_linux.go
