### ISSUE TITLE
Custom App using Display

### ISSUE THREAD

**Issue by lakshaygroverr** [balena-os/balena-engine#201]
Hi, I have a custom application written in python that is to show media using HDMI Display. Does BalenaOS allows users to run custom apps using display?

**Comment by robertgzr** [comment]
I think the forums would be the better place to ask for this: https://forums.balena.io/

Have a look at https://github.com/balenalabs/balena-dash as well, it might fit your use-case... if not it's a good guideline to follow for implementing something like that.
