### ISSUE TITLE
Migration of images/containers on aufs to overlayfs

### ISSUE THREAD

**Issue by robertgzr** [balena-os/balena-engine#205]
We want to enable exisiting containers to migrate from aufs to overlayfs graphdriver.

The scenario is a device that was deployed with aufs as the default graphdriver and is to be switched over to using overlayfs by default.
Currently this will require a full re-download of the container images and the existing containers to be destroyed and recreated.

**Comment by lmbarros** [comment]
@robertgzr , we can close this one, right?

**Comment by alexgg** [comment]
Storage migration is enabled since v2.84.0
