### ISSUE TITLE
Change /sys bind mount from ro to rw

### ISSUE THREAD

**Issue by chrisys** [balena-os/balena-engine#214]
When the `io.balena.features.sysfs` label is used to bind mount `/sys` into the container, currently the mount is created as read-only. It should be created as read-write to permit access to device peripherals without requiring a fully privileged container.

Further discussion here: https://www.flowdock.com/app/rulemotion/balenalabs/threads/vpx5ucMSw_Vcf9ye7BlOY1ANLgU

**Comment by robertgzr** [comment]
Changing the docker behavior here has some implications for what "unprivileged" means as full rw access to sysfs gives you quite a lot of access to the host system.

cgroupfs is under `/sys/fs/cgroup`, `/sys/kernel/*` exposes kernel info, etc.

**Comment by robertgzr** [comment]
The `io.balena.features.sysfs` label was introduced in balena-superviosr [version 10.8.0](https://github.com/balena-io/balena-supervisor/blob/master/CHANGELOG.md#v1080) and will bind mount `/sys` into the container, which should give full access to it.
