### ISSUE TITLE
How balena-engine data directory is protected against SD card corruption? (question)

### ISSUE THREAD

**Issue by ziXet** [balena-os/balena-engine#219]
It's been a while that I'm playing with Docker and Balena engine on RPi to find a good solution for deploying a safe production environment that can protect and survive from SD card corruption.

As far as I understand and experiment, there is no way that I can make the /var/lib/docker{balena-engine} directory read-only or using overlayfs with the lower read-only dir.

On the other hand, when you run a container with docker or balena, with every single process that gets executed in the docker container, I can observe a disk write to the device that mounted at /dev/lib/docker. I also tried to run the container with --read-only option but it did not make any difference.

Since balena-engine is being used in the Balena OS, how can you assure that the SD card corruption on the partition that holds the docker/balena-engine data-root won't affect the whole solution?

Thanks

**Comment by robertgzr** [comment]
I responded to your forums thread here: https://forums.balena.io/t/how-balena-engine-data-directory-is-protected-against-sd-card-corruption-question/118395/3

Let's continue the conversation over there :)
