### ISSUE TITLE
Encoding of raw bytes in journalctl logs

### ISSUE THREAD

**Issue by anujdeshpande** [balena-os/balena-engine#237]
User was wondering why some log messages were encoded as arrays of integers instead of strings. This is expected output from journalctl when messages contain non-utf8 or non-printable characters (\r in the case of a customer).

Is there something that can be done to better handle such cases?

**Comment by robertgzr** [comment]
I would not like to make any changes to the engine's log handling code that process the actual content like this. this will most likely come to bite us down the line in the shape of logging performance issues (as we've had before with the journald logger)
