### ISSUE TITLE
Unable to pull image from Dockehub

### ISSUE THREAD

**Issue by 22nishant** [balena-os/balena-engine#238]
**Description**
balena-engine pull command is not working with any registry including Dockerhub, AWS ECR.
Remaining commands for running the images and listing the images are working.

**Steps to reproduce the issue:**
1. Install balena-engine having version v17.12.0.
2. Run "balena-engine pull alpine:latest " command 

**Describe the results you received:**

error during connect: Post http://%2Fvar%2Frun%2Fbalena-engine.sock/v1.35/images/create?fromImage=alpine&tag=latest: EOF

**Describe the results you expected:**
latest: Pulling from library/alpine
801bfaa63ef2: Pull complete 
Digest: sha256:3c7497bf0c7af93428242d6176e8f7905f2201d8fc5861f45be7a346b5f23436
Status: Downloaded newer image for alpine:latest

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `balena-engine version`:**

```
Client:
 Version:	v17.12.0
 API version:	1.35
 Go version:	go1.10.4
 Git commit:	3fdfd0d
 Built:	Wed Oct 17 15:42:29 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	v17.12.0
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.10.4
  Git commit:	3fdfd0d
  Built:	Wed Oct 17 15:42:29 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```

**Output of `balena-engine info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 3
Server Version: v17.12.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null
 Log: journald json-file
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: runc bare
Default Runtime: runc
Init Binary: balena-engine-init
containerd version: 
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: N/A (expected: )
Security Options:
 apparmor
Kernel Version: 4.15.0-88-generic
Operating System: Ubuntu 18.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.56GiB
Name: ESYPC10
ID: YSTK:TBFF:55VZ:TW4U:FKL2:SO5O:XDRN:2KGA:TVDS:WZGB:KQK3:L6AD
Docker Root Dir: /var/lib/balena-engine
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

**Additional environment details (device type, OS, etc.):**

AMD64, Ubuntu 18.04

**Comment by NaveenD100** [comment]
I'm facing the slimier issue when I'm pulling the image.

**Comment by robertgzr** [comment]
Can you try with v18.09.10 from here: https://github.com/balena-os/balena-engine/releases/tag/v18.9.10
to see if the problem persists
