### ISSUE TITLE
ARMv6 machine pulls v7 image from manifest list

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-engine#269]
Upstream issue fixed in 20.10: https://github.com/moby/moby/issues/37647

Internal FD discussion: https://www.flowdock.com/app/rulemotion/r-beginners/threads/yRdloGy1nt802nvCe8PR8_akb6w

SO question: https://raspberrypi.stackexchange.com/questions/118612/running-docker-on-raspberry-pi-zero-w

Discovered on Pi Zero but other armv5 and armv6 devices would be impacted as well.

```bash
# Should return the date but the container just dies
$ balena run --rm alpine date
```

If you don't specify the platform with `--platform linux/arm/v6` or the registry path prefix `arm32v6/` it incorrectly downloads for arm32v7.

```bash
root@815b97b:~# balena pull alpine:latest
latest: Pulling from library/alpine
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest

root@815b97b:~# balena pull alpine:latest --platform linux/arm/7
latest: Pulling from library/alpine
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Image is up to date for alpine:latest
docker.io/library/alpine:latest

root@815b97b:~# balena pull alpine:latest --platform linux/arm/6
latest: Pulling from library/alpine
Digest: sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest
```

Impacts `balena build/deploy` and `balena push (local)` but not the builders as they specify the platform at build time.

**Comment by robertgzr** [comment]
closed by #270
