### ISSUE TITLE
Should update to moby v20.10.13 to get containerd v1.5.10

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-engine#300]
See: https://github.com/moby/moby/blob/v20.10.13/hack/dockerfile/install/containerd.installer#L18

**Comment by pascal-buchs** [comment]
I would recommend to update directly to: https://github.com/moby/moby/blob/v20.10.17/hack/dockerfile/install/containerd.installer 
Version 1.5 of containerd will already be out of life on october 2022: https://containerd.io/releases/#support-horizon
