### ISSUE TITLE
Balena requires device-mapper 1.02.1 to be installed`

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-engine#41]
Before running balena, one must install device-mapper 1.02.1. This can be done in debian/ubuntu with `apt-get install dmsetup`

**Steps to reproduce the issue:**
1. Install balena
2. Run `balena version`

**Describe the results you received:**
```
$ balena version
balena: error while loading shared libraries: libdevmapper.so.1.02.1: cannot open shared object file: No such file or directory
```
**Describe the results you expected:**
The version of balena.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

N/A

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
debian sid in a Dockerfile

**Comment by lurch** [comment]
I just tried running the x64 version of `balena` on my laptop running Ubuntu 14.04 (which admittedly isn't an IoT device!), and got a similar-but-different error:
```
$ ~/Downloads/balena/balena version
/home/andrew/Downloads/balena/balena: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory
```

**Comment by kennethlimcp** [comment]
```
odroid@odroid:~$ curl -sfL https://balena.io/install.sh | sh
[sudo] password for odroid: 
balena/balena-containerd-shim
balena/balena-containerd
balena/balena-proxy
balena/balena-runc
balena/balena-containerd-ctr
balena/balenad
balena/balena


   Installation successful!
 _           _
| |__   __ _| | ___ _ __   __ _
| '_ \ / _` | |/ _ \ '_ \ / _` |
| |_) | (_| | |  __/ | | | (_| |
|_.__/ \__,_|_|\___|_| |_|\__,_|

the container engine for the IoT
odroid@odroid:~$ balena
balena: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory
odroid@odroid:~$ uname -a
Linux odroid 3.10.80-131 #1 SMP PREEMPT Thu Oct 15 19:53:29 BRT 2015 armv7l armv7l armv7l GNU/Linux
odroid@odroid:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
odroid@odroid:~$ 
```

**Comment by dbalakirev** [comment]
Same, on Red Hat Enterprise Linux 7 desktop (which might or might not be supported anyway).

**Comment by stefanKnott** [comment]
Any suggestions/fix for this?  Im running into this as well on RHEL 7

**Comment by robertgzr** [comment]
Since https://github.com/balena-os/balena-engine/commit/b64eefe3a2fe7311d27f8a1a6a24565ba005e6f2 we distribute statically linked binaries

Updating to [balenaEngine v17.12](https://github.com/balena-os/balena-engine/releases/tag/v17.12.0) fixes this.
