### ISSUE TITLE
Container fails to start after Engine crash with error `task <UUID> already exists`

### ISSUE THREAD

**Issue by lmbarros** [balena-os/balena-engine#435]
The exact circumstances around this issue are not 100% clear, but here is our current understanding:

* balenaEngine and the containers were running smoothly.
* Something happens that causes the Engine to crash.
* When restarting, the Engine fails to re-start one or more of the containers, with the error `task <Container UUID> already exists`.

According to our debugging, what is happening is that the Engine internal state is getting inconsistent during this crash/restart cycle. Specifically, upon restart containerd seems to believe that the task (i.e., the process running in a container) is still running, which is not true. It then raises an `ErrAlreadyExists` error (defined in `vendor/github.com/containerd/containerd/errdefs/errors.go`), which is what surfaces in the logs.

Overall, this error seems to be a very rare occurrence, but in one customer this is pretty frequent. According to our analysis, this customer is getting into a situation in which the device gets into a state of high resource usage (especially CPU). Containers health check start to fail, and so containers are restarted. This adds even more load to the system, which spirals down until a point in which the Engine crashes. This seems to be a perfect storm to trigger this bug: Engine crashing while multiple containers are being restarted themselves.

**Comment by lmbarros** [comment]
Created the [lmb/issue-435 branch](https://github.com/balena-os/balena-engine/tree/lmb/issue-435) to work on this issue. For now, I am using it to take notes at relevant points while analyzing the issue.

**Comment by lmbarros** [comment]
I think I found something promising. containerd keeps information about running containers in two different locations. So, for a given container, we'd have stuff in these two dirs:

* `/var/run/balena-engine/containerd/daemon/io.containerd.runtime.v1.linux/moby/<UUID>
* `/var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/<UUID`

The [code doing the cleanup](https://github.com/balena-os/balena-engine/blob/lmb/issue-435/vendor/github.com/containerd/containerd/runtime/v1/linux/bundle.go#L178) when a container is stopped removes each of these directories atomically, but we can still crash *between* these two atomic removals.

I prepared an Engine release modified to crash (opt in :wink:) at that point. I had a more structured test in mind, but I actually got my crashing code triggered while I was preparing the device for the test.

Since I got into this while I was not expecting, I am not sure what were my steps exactly. Anyway:

```
# balena start ded5d899febd
Error response from daemon: task ded5d899febd88e0f2f076aee9deac87452cfd6acbfaec90ff503246ef901770: already exists
Error: failed to start containers: ded5d899febd
```

There's our error!

**Comment by lmbarros** [comment]
Now, sadly this doesn't seem to be the whole answer yet.

I would expect that removing any `ded5d8...`  leftovers from both those locations would work around the issue and allow the container to start, but it doesn't. Therefore, there must some more metadata persisted elsewhere, which would imply in more points where crashes would cause this exact error. (Corollary: our critical session is larger than that function I linked in my previous comment.)

**Comment by lmbarros** [comment]
But here's something to think about: that code is part of containerd's runtime v1, which we indent to replace with v2 anyway.

I don't know if v2 would avoid the issue, but glancing over the implementation, it's clear the logic got more involved and the method even got a  [`Delete a bundle atomically` comment](https://github.com/balena-os/balena-engine/blob/9c9e1690d95b6d4e41ba656a98ecf41657bb8150/vendor/github.com/containerd/containerd/runtime/v2/bundle.go#L118).

Even this is indeed atomic, the issue might still exist (e.g., because of the things I said in my previous comment). But it looks like a step forward, and one we intend to take anyway.

At this point, it seems that the smarter way is to first focus on the migration to v2, because any effort put into v1 would be short-lived.

**Comment by lmbarros** [comment]
Just did some tests with a newer version of balenaEngine -- one that is already updated to the runtime v2. As in my previous test, I modified the Engine to force crashes at critical points in the [`bundle.Delete()` method](https://github.com/balena-os/balena-engine/blob/9c9e1690d95b6d4e41ba656a98ecf41657bb8150/vendor/github.com/containerd/containerd/runtime/v2/bundle.go#L118). In other words, doing the same test as before, but with the new Engine version.

I tried force-crashing in four different points, and in none of them I ran into the `task <UUID> already exists` error when restarting the container.

I'll give a bit more thought on other things we could test, but the updated Engine is looking good so far!

**Comment by lmbarros** [comment]
For reference, this updated Engine is available in balenaOS 4.0.11 and later.

**Comment by louisburton** [comment]
Leandro - thank you! That is great news.

**Comment by louisburton** [comment]
This appears fixed to us in the latest engine update

**Comment by lmbarros** [comment]
Thanks for testing this and coming back to us with the results, @louisburton ! Super happy to see this is solved!

**Comment by himanchops** [comment]
Hi, I can see this issue manifest for some of our devices in the field still. They're running balenaOS 4.0.25.
