### ISSUE TITLE
build.sh uses different version than the make script it calls

### ISSUE THREAD

**Issue by imrehg** [balena-os/balena-engine#44]
When running `build.sh`, the version is inferred from git commit. The script it calls, though, `hack/make.sh`, uses the `VERSION` file in the root to infer the version to build. These two can be out of step with each other (e.g. building from the tag `17.06-rev1` would try to build as `17.06.0-dev`.

Some sort of reconciliation of these two versions might be desirable? Just updating VERSION is not enough, because then `make.sh` complains of uncommitted changes.

**Comment by robertgzr** [comment]
this is invalid as of https://github.com/balena-os/balena-engine/releases/tag/v17.12.0
which has https://github.com/moby/moby/pull/35368
