### ISSUE TITLE
Expand the install script

### ISSUE THREAD

**Issue by nmaas87** [balena-os/balena-engine#51]
It would be awesome if the install script would also contain a systemd service file, create a group for balena, give advice on adding the current user to said group and then start balenad from the service, similiar to the Docker install script

**Comment by vpetersson** [comment]
I ran into the exact thing. I thought the installer had silently failed, but turns out it was the expected behavior. Personally, I'd also like to see a symlink from `docker` to `balena` too in order to make the transition smoother.

**Comment by robertgzr** [comment]
Instead of bringing the service files as part of the install script, it will point to the exact locations of the init service files for the intalled release
