### ISSUE TITLE
Link to star on github from balena.io landing page is incorrect

### ISSUE THREAD

**Issue by alisondavis17** [balena-os/balena-engine#68]
The button/link to star on GitHub on the balena.io landing page does not work as expected. 

It is incorrectly linked to https://buttons.github.io/buttons.html#, and nothing happens when the button is clicked. 

![screen shot 2017-12-22 at 7 03 03 am](https://user-images.githubusercontent.com/20308284/34302600-77669bd4-e6e6-11e7-8d40-c678206960a3.png)

It should link directly to the [balena repo](https://github.com/resin-os/balena/) on GitHub and open the repo page in a new tab upon clicking the button. Ideally, it should also show the number of existing stars next to the button, similar to the behavior on etcher.io

![screen shot 2017-12-22 at 7 05 23 am](https://user-images.githubusercontent.com/20308284/34302611-86513910-e6e6-11e7-84b7-b54c7120c69a.png)

**Comment by robertgzr** [comment]
The balenaEngine page moved to https://balena.io/engine

After the redesign this issue is not valid anymore...
