### ISSUE TITLE
Balena did not create bind mount sources on container creation

### ISSUE THREAD

**Issue by CameronDiver** [balena-os/balena-engine#78]
**Description**

On starting a container, the `/tmp/resin-supervisor/services/<appid>/main` directory was not created. This meant that the update lock could not be taken (as the only way of successfully writing to `/tmp/resin` from within the container was to first umount it.

```
{
  "Type": "bind",
  "Source": "/tmp/resin-supervisor/services/<appid>/main",
  "Destination": "/tmp/resin",
  "Mode": "",
  "RW": true,
  "Propagation": "rprivate"
},
```

**Steps to reproduce the issue:**
* Start a container with a bind mount that doesn't exist.
* Sometimes that bind mount will not be created.

**Describe the results you received:**

The source location for the bind mount was not present.

**Describe the results you expected:**

The source location for the bind mount to have been created by balena.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue only happens occassionally

**Output of `balena version`:**

```
root@e8e0eb4:~# balena version
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.9
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   73136d1985f28a34705f537e90636cf208734048
 Built:        Tue Mar 13 17:13:43 2018
 OS/Arch:      linux/arm
 Experimental: true
```

**Output of `balena info`:**

```
root@e8e0eb4:~# balena info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.06.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 52
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan null
 Log: journald json-file
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-init
containerd version:  (expected: 3addd840653146c90a254301d6c3a663c7fd6429)
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: 949e6fa-dirty (expected: 949e6facb7738)
Kernel Version: 4.9.59
Operating System: Resin OS 2.12.3+rev1
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 748.9MiB
Name: e8e0eb4
ID: HEPW:BIQR:WN74:RAMM:ZGQE:YS3A:DKSE:FHQC:HI4B:UFWL:GHZD:K35D
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_amgj)

**Comment by pcarranzav** [comment]
Note that we do not know if the folder wasn't created or was created and then deleted

**Comment by robertgzr** [comment]
closed by https://github.com/balena-os/meta-balena/issues/1377
