### ISSUE TITLE
Question: docker-compose.yml support

### ISSUE THREAD

**Issue by vitosans** [balena-os/balena-engine#83]
Any plans to support docker-compose.yml for launching services?

**Comment by cnrmck** [comment]
[Multicontainer support](https://www.balena.io/docs/learn/develop/multicontainer/)

**Comment by robertgzr** [comment]
As pointed out by @cnrmck balenaCloud has support for multicontainer applications, for more info on that see the link he posted.

If you want to use the `docker-compose` cli directly you can point it to balenaEngine via the `DOCKER_HOST` environment variable or the `--host` cli option 
(see https://docs.docker.com/compose/reference/overview)

**Comment by macpijan** [comment]
If someone gets here through Google as I have - something like that worked for me:

```
docker-compose --host unix:///var/run/balena-engine.sock up
```
