### ISSUE TITLE
Balena engine with Kubernetes

### ISSUE THREAD

**Issue by sureshsankaran** [balena-os/balena-engine#84]
I am trying to run kubernetes on my cluster and want to have Balena as my container runtime. But kubelet is not starting up with Balena engine. Does Balena have cri shim layer to talk to kubelet ? Is it compatible with kubernetes?

**Comment by kushwahakunal** [comment]
since balena api's are same as docker, I think it should work, though not personally tested.

Kubelet have inbuild CRI implementation called  `dockershim `, which is enabled by default.
You may try configuring kubelet with  `--docker-endpoint ` to  `/var/lib/balena.sock ` .

**Comment by robertgzr** [comment]
As pointed out by @kushwahakunal you should be able to use `dockershim` after you pointed it to the correct endpoint.

_Note that if you're using balenaEngine [v17.12](https://github.com/balena-os/balena-engine/releases/tag/v17.12.0) and later the right location is `/var/run/balena-engine.sock`_

**Comment by Slin25** [comment]
Since Kubernetes is deprecating Docker and the old CLIs has anyone been able to set balena-engine as the container runtime?
