### ISSUE TITLE
Slow balena pull

### ISSUE THREAD

**Issue by antonmolodykh** [balena-os/balena-engine#86]
**Description**

We want to use Balena in Screenly OSE, however I noticed that `balena pull` works *much* slower than `docker pull`

**Steps to reproduce the issue:**
1. `balena pull screenly/screenly-ose-viewer`
2. `docker pull screenly/screenly-ose-viewer` (on a fresh sd card)
3. compare time

**Describe the results you received:**
`balena pull` works *much* slower than `docker pull`

**Describe the results you expected:**
`balena pull` works faster, because it was specially built for embedded and IoT use cases

**Additional information you deem important (e.g. issue happens only occasionally):**
I tested it twice. For the tests purity, I used one device (Raspberry Pi 3 Model B+), one sd-card, and the same type of connection (wi-fi)
This is my comparative table:

| Pull tests | Test 1 | Test 1 | Test 2 | Test 2   |
|---------------------------------|--------|--------|--------|----------|
|  | Docker | Balena | Docker | Balena   |
| screenly/screenly-ose-viewer    | 10:15  | 16:24  | 10:12  | 40:07(!) |
| screenly/screenly-ose-server    | 4:44   | 7:36   | 5:04   | 16:35    |
| screenly/screenly-ose-websocket | 3:17   | 5:10   | 3:09   | 10:08    |

**Output of `balena version`:**
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.9
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/arm

**Output of `balena info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null
 Log: journald json-file
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-init
containerd version:  (expected: 3addd840653146c90a254301d6c3a663c7fd6429)
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: N/A (expected: )
Kernel Version: 4.14.34-v7+
Operating System: Raspbian GNU/Linux 9 (stretch)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 808.3MiB
Name: raspberrypi
ID: VXIV:OAS3:ZY2D:356C:KGYI:B7DB:OI5Q:5Y5V:S54K:Z2XK:ZTRE:AZPI
Docker Root Dir: /var/lib/balena
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vpetersson** [comment]
I had a chat with @alexandrosm about this - likely related to the `fsync` changes.

**Comment by nabbott2008** [comment]
I have installed on 2 systems and still seeing very slow performance on balena pulls compared to docker pulls.

Here are tests with both starting with empty local image repos:

root@ubuntu:~# time docker pull centos:7
7: Pulling from library/centos
aeb7866da422: Pull complete
Digest: sha256:67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
Status: Downloaded newer image for centos:7

real    0m21.936s
user    0m0.017s
sys     0m0.013s

root@ubuntu:~# time balena pull centos:7
7: Pulling from library/centos
aeb7866da422: Pull complete
Total:  [==================================================>]   74.7MB/74.7MB
Digest: sha256:67dad89757a55bfdfabec8abd0e22f8c7c12a1856514726470228063ed86593b
Status: Downloaded newer image for centos:7

real    1m0.740s
user    0m0.044s
sys     0m0.013s

root@ubuntu:~# balena version
Client:
 Version:      unknown-version
 API version:  1.31
 Go version:   go1.9
 Git commit:   unknown-commit
 Built:        unknown-buildtime
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-dev
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.9
 Git commit:   c6df57f
 Built:        Fri Oct 13 09:05:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@ubuntu:~# balena info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.06.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/balena/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null
 Log: journald json-file
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Runtimes: bare runc
Default Runtime: runc
Init Binary: balena-init
containerd version:  (expected: 3addd840653146c90a254301d6c3a663c7fd6429)
runc version: 13e66eedaddfbfeda2a73d23701000e4e63b5471
init version: N/A (expected: )
Security Options:
 apparmor
Kernel Version: 4.15.0-36-generic
Operating System: Ubuntu 18.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.947GiB
Name: ubuntu
ID: DEHM:WNJC:VSCY:MKFH:UZ3W:H77S:T3CH:D6YO:Z4OB:W7LF:DP3B:E2IK
Docker Root Dir: /var/lib/balena
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 xxxxx
 xxxxx
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

Tested from a virtualbox VM and from a dedicated server and have same results.

**Comment by robertgzr** [comment]
Resolved with #159 

See https://github.com/balena-os/balena-engine/issues/133#issuecomment-487023162
