### ISSUE TITLE
no systemd

### ISSUE THREAD

**Issue by vitosans** [balena-os/balena-engine#87]
I am wanting to use balena for embedded devices but my systems will not have systemd - right now its looking for libsystemd - any plans for just openrc or sysv init?

**Comment by christopherhex** [comment]
Having similar issues.

I would like to use `balena` within an alpine container to access the host `balena` daemon.
Is also complaining about no `systemd` present when I try to run it.

**Comment by selvakn** [comment]
have a look at https://github.com/resin-os/balena/blob/17.06-resin/contrib/init/systemd/balena.service

**Comment by robertgzr** [comment]
There is no hard requirement to run on a system that has systemd - assuming you don't want to use the journald logdriver

@vitosans @christopherhex if you could provide us with some logs that would be helpful
