### ISSUE TITLE
Support flexible/wildcard device additions to non-privileged containers

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-engine#97]
In some cases it would be good to be able to define a range of devices or type of device to be added to the container /dev. One example of this would be in the case of a usb serial device where its not always known at deploy type what the usb device would enumerate too. Allowing something like specifying `--device ttyUSB*:ttyUSB0` or something similar to that would be very useful.

**Comment by robertgzr** [comment]
We intend to expose a synced view of `/dev` to the container, as such this is a duplicate of #125
